services:
  import-build-cron:
    build: .
    restart: always
    volumes:
      - '.:/app'
      - 'node-modules:/app/node_modules/'
      - 'yarn-cache:/usr/local/share/.cache/yarn/'
    working_dir: /app
version: '3.1'
volumes:
  node-modules: null
  yarn-cache: null
